package com.pintu.xcelpractice;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import java.util.Map;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.DateUtil;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 * Hello world!
 *
 */
public class App 
{
	public static final String FILE_NAME = "D:\\spring projects\\xcelpractice\\src\\main\\java\\com\\pintu\\xcelpractice\\ExpensesTracker.xlsx";
    public static void main( String[] args ) throws IOException, ParseException
    {
    	Date date1;
    	List<Map<String,String>> excelMapList = new ArrayList<Map<String, String>>();
    	Map<Integer,Map<String,String>> globalMap = new HashMap<Integer, Map<String, String>>();
    	List<String> keyList = new ArrayList<String>();
    	List<Expenses> expensesList = new ArrayList<Expenses>();
    	System.out.println( "Hello World!" );
    	FileInputStream excelFile = new FileInputStream(new File(FILE_NAME));
    	Workbook workbook = new XSSFWorkbook(excelFile);
        Sheet expensesSheet = workbook.getSheetAt(0);
        Iterator<Row> rowIterator = expensesSheet.iterator();
        boolean isNotGeneratedKeys = true;
        int i =0,j =0;
        while (rowIterator.hasNext()){
        	Map<String, String> excelMap = new HashMap<String, String>();
        	Expenses expenses = new Expenses();
        	Row currentRow = rowIterator.next();
        	Iterator<Cell> cellIterator = currentRow.iterator();
        	if (isNotGeneratedKeys) {
        		while (cellIterator.hasNext()) {
        			keyList.add(cellIterator.next().toString());
        		}
        		isNotGeneratedKeys = false;
        		continue;
        	}
        	
        	while (cellIterator.hasNext()) {
        		Cell currentCell = cellIterator.next();
        		if (keyList.get(i).equalsIgnoreCase("Date")) {
        			if (!DateUtil.isCellDateFormatted(currentCell)) {
        				date1 = new SimpleDateFormat("MM/dd/yyyy").parse(currentCell.toString());
            			currentCell.setCellValue(date1.toGMTString());
        			}
        			expenses.setDate(currentCell.getDateCellValue());
        		} else if(keyList.get(i).equalsIgnoreCase("Spent for")) {
        			expenses.setSpentFor(currentCell.getStringCellValue()); 
        		} else if(keyList.get(i).equalsIgnoreCase("Amount")) {
        			expenses.setAmount(currentCell.getNumericCellValue());
        		}
        		/*if ((CellType.NUMERIC == currentCell.getCellTypeEnum()) && DateUtil.isCellDateFormatted(currentCell)) {
        			System.out.print(currentCell.getDateCellValue()+"\t");
        		}*/
        		
        		/* if (CellType.STRING == currentCell.getCellTypeEnum()) {
        			 excelMap.put(keyList.get(((ListIterator<Cell>) cellIterator).nextIndex()), currentCell.toString());
        			System.out.print(currentCell.getStringCellValue()+"\t");
        		} else if (CellType.NUMERIC == currentCell.getCellTypeEnum()) {
        			excelMap.put(keyList.get(((ListIterator<Cell>) cellIterator).nextIndex()), currentCell.toString());
        			System.out.print(currentCell.getNumericCellValue()+"\t");
        		}*/
        		 excelMap.put(keyList.get(i), currentCell.toString());
        		 i++;
        	}
        	globalMap.put(j, excelMap);
        	expensesList.add(expenses);
        	j++;
        	i=0;
        }
        //excelMapList.forEach(excelMap-> ());
      // Map<String, String> excelMap = new HashMap<>();
        //excelMapList.forEach(excelMap->System.out.println(""));
       // excelMap.forEach((k,v)->System.out.println("Key : "+k+"Value "+v));
        keyList.forEach(key-> System.out.print(key+"\t"));
        System.out.println();
        globalMap.forEach((index, item) -> {
        	item.forEach((k, v) -> System.out.print(v+"\t"));
        	System.out.println();
        });
        keyList.forEach(key-> System.out.print(key+"\t"));
        System.out.println();
        expensesList.forEach(expenses->System.out.println(expenses.getDate()+"\t"+expenses.getSpentFor()+"\t"+expenses.getAmount()+"\n"));
        
    }
}
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        		 
        
